/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** Type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export interface paths {
  "/{section}.json": {
    /**
     * Top Stories 
     * @description The Top Stories API returns an array of articles currently on the specified section.
     */
    get: {
      /**
       * Top Stories 
       * @description The Top Stories API returns an array of articles currently on the specified section.
       */
      parameters: {
          /** @description The section the story appears in. */
        path: {
          section: "arts" | "automobiles" | "books" | "business" | "fashion" | "food" | "health" | "home" | "insider" | "magazine" | "movies" | "nyregion" | "obituaries" | "opinion" | "politics" | "realestate" | "science" | "sports" | "sundayreview" | "technology" | "theater" | "t-magazine" | "travel" | "upshot" | "us" | "world";
        };
      };
      responses: {
        /** @description An array of articles. */
        200: {
          content: {
            "application/json": {
              status?: string;
              copyright?: string;
              section?: string;
              last_updated?: string;
              num_results?: number;
              results?: (components["schemas"]["Article"])[];
            };
          };
        };
        /** @description Unauthorized request.  Make sure api-key is set. */
        401: {
          content: {
          };
        };
        /** @description Too many requests.  You reached your per minute or per day rate limit. */
        429: {
          content: {
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    Article: {
      section?: string;
      subsection?: string;
      title?: string;
      abstract?: string;
      url?: string;
      uri?: string;
      byline?: string;
      item_type?: string;
      updated_date?: string;
      created_date?: string;
      published_date?: string;
      material_type_facet?: string;
      kicker?: string;
      des_facet?: (string)[];
      org_facet?: (string)[];
      per_facet?: (string)[];
      geo_facet?: (string)[];
      multimedia?: ({
          url?: string;
          format?: string;
          height?: number;
          width?: number;
          type?: string;
          subtype?: string;
          caption?: string;
          copyright?: string;
        })[];
      short_url?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
